# Generated by Django 2.1.7 on 2019-04-01 01:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0002_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='check',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
