# Generated by Django 2.1.7 on 2019-04-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0003_auto_20190401_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
