# Generated by Django 2.1.7 on 2019-04-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0004_auto_20190401_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
